### ISSUE TITLE
conflicting with "tab terminal"

### ISSUE THREAD

**Issue by pinggit** [sillybun/vim-repl#94]
start vim
open a file
start REPL
start a new terminal in a new tab

```
vim
:edit file1.pl
:REPLtoggle
:tab terminal
```

now, if you switch between terminal tab and other tab back and forth (try gt then gT , and gt), the terminal tab will be closed.
once the REPL buffer get closed, the issue won't appear.
I can reproduce this easily. I think it is a bug.

**Comment by sillybun** [comment]
I can repro this bug. But I have no idea how to fix it.

**Comment by rittelle** [comment]
This behavior is caused by the condition inside `autocmd`: https://github.com/sillybun/vim-repl/blob/22a8c5518b9c08b69ad531cef4ba6ec953b5154a/autoload/repl.vim#L281
It matches any vim terminal window as long as a REPL buffer is opened. So here's what happens in the example above:
1. `REPLOpen` (called by `REPLToggle`) sets up the `autocmd`
2. `: tab terminal` creates a tab page with only 1 window (`winnr("$") == 1`)
3. gt, gt triggers the `autocmd`: There is only 1 window on the tab, a buffer with a REPL exists and the current buffer is a terminal: `:q` is executed and the tab page is gone

Came across this by accident while doing my neovim porting :) .
